language: node_js

cache: yarn

node_js:
  - 8
  - 10

before_install:
  - npm i -g yarn

script:
  - yarn build
  - yarn test

notifications:
  slack:
    secure: nhoO1GyN9Y691FJUk6OqCv+nywgEG6cze3vEQALKI+2kgvW2YNqbxAEnZcSrh2rn4bUB0Dm8Y+H1yrTE1jLHFlnPneNgUps93YJgqn4cumBRVjrPZCD1Uc4A+563u3PLk+/+4JvPGKZHPkPMlZyBhr2hUHsuuZngeQKtPJKG7LC+jIucKtST/ceAO5cjkwikdVo026UeobE6rDTxrmSH4hmUxD+JkOSNVHkBoK3Byr4fSnx4vTfp4tA4SRVer6Jh48A8Man3HS+CPDHBRw3x31ewmsJeEQD8iDCeQ9IEJHMB5wSCKX9gHzMe3+vkndD7tyScuOl+S58/Wt+JmgBEAZSR5SWLMuYxmcWMfvt4uqfQokYgwOx5kiOAP+89OECfKuSXFvNdn4HkkrKsbm4PHxphJBcpMj9c3pX5Xl08uBBiv0d+tl27c2mkInwOdbRxpp70C2Qd3EfMpNxxUIo4/FiK4fQS5QuzMirt6AY5YGtZYsqeAFhbA6x+J5gbMesmRJDdKHKv3g9BitQLZ02nepWEf/SurOhrsIUYin408PxHVzHB6JCndPNGTyCznfpqr+3HIkxJ0cRsTHqTIEWyMkWLtIDKc3UcWhGB12HTi2RYpA2g1gNbPCJBxhfel5dmJhw5P+8bdsVVAPlcgK8JaSU1QcbnzH5s1p2DXvyrgv4=

env:
  global:
    - secure: oVdtXvGIRMLoxqynPbLyUaiSb/h6TEDWkR0+WoffBh/Jcy3n3IUI0KgG6yr2Pl2UJQADWpUBebSjhnuGHCni9qey5rorhwnDU13XqGz0WamRWJRR/UzBSa0flDanbzQGRfsu1HwcB1iIN6hC4jvS3vv+FRZwRUEzDSB8Gl/n6EysnUk68xvvCRryXyF7VSOU6SGMgddhxRKRCDSJ9cxmOtnzp9TjbrCdQcTXz1+AKFqJDM2y3RwNf8BYJJSpWMQz7Fk9L49YWTZ7coB3uS3QU2KDtTBrSw14xeRpYBRSdmHQlsCPGvsJehCfbSfTiNoanfFwTXzXZJlcQyHt+TFYtketimhkH/Y21UIC7aQ/i1H7Yrbb0I3Q4+gUR0FHo7UkLPDEtl5+5/vdppUPO4J8msUU7h2V6LuJvrNUOmbJOIydMOGKAcAVYAnhc+iBMWzfpOYeaw+R3S/S/I65ky6bn5Lsk7F1Vv8pLDGYlRwUACaVEXj0p65gTDH6Nl8Nj1+lCIPRX9hV/xeaAW+A4igi168WAidZkvz05rLXWIZFS38igLmvXd+/KpaLUsSPyEfRB1qeoQ8rnQeB5MYRysxf6jXcEU58PHW0DueWJ+7ADHOVyzKEYltlJQO/AVrvXufv697opWZ4U20phOemRryCwEmZvxQsK2xTCiz5F01C9AQ=
    - secure: L3h8d9+Azw5s9Y4LXVFBZBIdnpW8PKjp//qx2e2wDdJhfJPENHJR7w4KRbERFps3T3GmaoBn5vLEqo0WNu96cAVYYhIFzi/rd75sdEaZ0AiA5Als1Rqqxbp30mlsmqV7dYmXY1TYR2/zhUFRF+eaQJBLxX+fk8sf6ldgiclpc9LyJz5yJeo6pSXdeEC24yjLaV5cgiOrysoLS8WMcBWeW9mPzCYLDQo5lT6EcO24RSXYdCbEf7hhHopoBo0ZZsfyPzs+Etmx+CVOZ/V7IeDTPjYwvgVAE5DZVy/aW4ne3A/CJyDv1UTa/CSt2vppk7AMw0NAIfn7LgBGwvppWXAPeIpxP2O3z09OJ3co5X/2+t8L8qGYm/pehmsF8hR8lbACUcBFr+3gDxal99VwOh+Al7hr9r9ZqJ7jeyzYur9y0dAp+DKXWxCJ8m4YLP7AZAz9o7ml7MWCwqAfhxO1zTgspkJNiGrJY/X0w/tTouma6wleCistWEVl083c+DjndNonYwLGzJavG/DSPExsdkSXblgvsJwVqqPWPKagpEkvIZg5LvljqoxvTZ7SCdLcYTVJn+OWlSw3G3gTiMby/a8Yx8Eh6D/Y2F+ai0bdIKc77+uHcW1pLobZBVXcB0+E2EqTxsorHfqmEVIvMQWd5IVQ6gGXZn+1rkqutqGaMudz8kc=
    - secure: Rn0Az3UWePkRVlt42dv2DTodrS67SbsgHApyswWqQxc6lnqe1BmQYYoI+iA7/hpfqPcyUpvX5j+GuyxS7E6YTGWqJVpYiCpSALy9T2A9k/hwVtALuS9OtDE5IEEG3diPVoBwnZixLE3SkvL3uwcYqv3LL6VkHTg3zb+3iI+8CrMEMkTm6e9Ebyg7TcYVbk6VpZ25CIChuJe+8zpkCF/n1dN6GcueV6V/qVId/nvQRpg4sd4RF2nzQIvQ+kIfgypfQY7PDaN1ZUOafxxm6giKp8ffpA5muvR2CI1NyKrlLGZhSjy14A1R79+ZF2JRzkTcDDC1r2h6kksJwZW1MOmULGTNnW/gZc981+WJU1P5GIOSuOKkGMvW/VlMLvbz2TvpVKnv4gOv469+3zXfsCVz/aHUyOePSKpXcJzIgSC2eUD6167lkoQxbw0mutVskmgPXXwA52ONro0DefT5VC4FWtnw+5s2yHa7Kx3frv3Bh4BdnRoIvo7qvMwvzUrbnRz4sDrRdCn8EwPPyaH1q4/F09b+himxJB8s9CUr6jOa7EoBdqNR5cL+UIzrIWplgX+1HsdHTgyIT3xwQSjYjUbJ2tQ4rFV7mZszlsxoO37x0nalo6QEkY2E5PvQBHhlA7SIbEasF5V5v0WeJ30RS46LByaWxC06Nykbf7GvdwRXsw4=
    - export GIT_AUTHOR_NAME="EndemolShineGroupUser"
    - export GIT_AUTHOR_EMAIL="tech@endemolshine.com"
    - export GIT_COMMITTER_NAME="EndemolShineGroupUser"
    - export GIT_COMMITTER_EMAIL="tech@endemolshine.com"

jobs:
  include:
    - stage: coverage
      if: type != pull_request
      before_script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
      after_script:
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
      after_success:
        - yarn global add codecov
        - codecov
    - stage: release
      if: branch = master AND type != pull_request
      after_success:
        - yarn semantic-release
        - git clone https://${GH_TOKEN}@github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
        - cd $TRAVIS_REPO_SLUG
        - git fetch --all
        - git merge origin/master
        - git push
